export  const INIT_HOME_DATA = 'init_home_data';
export  const INIT_RECENT_UPDATE_ALL = 'init_recent_update_all';
export  const INIT_RECENT_UPDATE_FREE = 'init_recent_update_free';
export  const INIT_RECENT_UPDATE_VIP = 'init_recent_update_vip';
export  const IS_ALL='is_all';
export  const IS_FREE='is_free';
export  const IS_VIP='is_vip';
export  const INIT_SEARCH_DATA = 'init_search_data';
export  const INIT_SEARCH_DATA_FIX = 'init_search_data_fix';
